version: "3"
services:
  node-app:
    container_name: express-node-app-container #I remove name of container bec.. load balancing
    #image: alezz77122/dockerfiles
     #build: .
    ports:
       - "4000:4000" #because load balancing using inginx forword traffic on port 8080 for all container
    env_file:
      - ./.env
    #deploy:
    #  replicas: 4
    #  update_config:
    #    parallelism: 2
    #    delay: 10s
    #  restart_policy:
    #    condition: on-failure
    #    delay: 5s
    depends_on:
      #- postgres
      - mongo
      - redis
  #  postgres:
  #    image: postgres
  #    restart: always
  #    volumes:
  #      - postgres-db:/var/lib/postgresql/data
  #    environment:
  #      POSTGRES_USER: root
  #      POSTGRES_PASSWORD: example

    mongo:
      image: mongo
      restart: always
      volumes:
       - mongo-db:/data/db
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: example

  #mongo-express:
  #  image: mongo-express
  #  restart: always
  #  ports:
  #    - 8081:8081
  #  environment:
  #    ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #    ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #    ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
  #  depends_on:
  #    - mongo

  redis:
    image: redis

  nginx:
    image: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node-app

volumes:
  mongo-db:
#  postgres-db:
